"""Practicing relational operators."""
__author__ = "730392344"
left_hand_side: str = input("Left-hand side: ")
right_hand_side: str = input("Right-hand side: ")
int(str(left_hand_side))
int(str(left_hand_side))
less_than = bool(left_hand_side < right_hand_side)
at_least = bool(left_hand_side >= right_hand_side) 
equal_to = bool(left_hand_side == right_hand_side) 
not_equal_to = bool(left_hand_side != right_hand_side)
less_than = str(less_than)
at_least = str(at_least) 
equal_to = str(equal_to)
not_equal_to = str(not_equal_to) 
print(left_hand_side + " < " + right_hand_side + " is " + less_than)
print(left_hand_side + " >= " + right_hand_side + " is " + at_least)
print(left_hand_side + " == " + right_hand_side + " is " + equal_to)
print(left_hand_side + " != " + right_hand_side + " is " + not_equal_to)
